site:
  title: ThoughtSpot Documentation
  url: https://help-software.vercel.app
  start_page: home::index.adoc
content:
  sources:
  # embedding empty credentials in the URL disables the Edit this Page link for any page created from this repository
  - url: .
    branches: HEAD
    start_path: home
  - url: git@github.com:thoughtspot/thoughtspot-docs.git
  # Software docs branches
    branches: ['9.0.1.sw','9.5.0.sw','9.8.0.sw','10.1.0.sw']
    start_path: software/
# urls:
#  latest_version_segment_strategy: redirect:to
#  latest_version_segment: latest

ui:
  bundle:
    # url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    url: ui-bundle/uidev-bundle.zip
  supplemental_files:
  - path: .nojekyll
  - path: ui.yml
    contents: "static_files: [ .nojekyll ]"
    snapshot: true
asciidoc:
  attributes:
    #software: true
    #cloud: false
    help: ''
    page-company: ThoughtSpot
    tabs: tabs
    support-url: https://community.thoughtspot.com/customers/s/contactsupport[ThoughtSpot Support^]
    seekwell: SeekWell
    cl-subscription-agreement: https://www.thoughtspot.com/legal/thoughtspot-cloud-subscription-agreement[subscription agreement^]
  extensions:
  - "@djencks/asciidoctor-tabset-block"
output:
  clean: true
  dir: build/
runtime:
  fetch: true
  log:
    level: error
